#place where test the api with the help of http request

### TEST USER API

### Test login successfully with valid credentials
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "mario@test.it",
    "password": "pwd"
}

### Test fail login with invalid credentials
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "invalidUser",
    "password": "invalidPassword"
}

### Test logout successfully
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "marco@test.it",
    "password": "pwd"
}

DELETE http://localhost:3001/api/sessions/current

### Test checking current session when authenticated
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "mario@test.it",
    "password": "pwd"
}

GET http://localhost:3001/api/sessions/current

### Test checking current session when not authenticated
DELETE http://localhost:3001/api/sessions/current

GET http://localhost:3001/api/sessions/current


### TEST DOCUMENT API

### test insertion of document if urban planner

POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "mario@test.it",
    "password": "pwd"
}

POST http://localhost:3001/api/documents
Content-Type: application/json

{
    "title": "Sample Document",
    "idStakeholder": 1,
    "scale": "National",
    "issuance_Date": "04/2019",
    "language": "English",
    "pages": 50,
    "description": "Description of the document.",
    "idtype": 2
}

### test insertion of document if not authenticated or not urban planner


DELETE http://localhost:3001/api/sessions/current

###
POST http://localhost:3001/api/documents
Content-Type: application/json

{
    "title": "Sample Document",
    "idStakeholder": 1,
    "scale": "National",
    "issuance_Date": "04/2019",
    "language": "English",
    "pages": 50,
    "description": "Description of the document.",
    "idtype": 2
}

# 401 Unauthorized
# {
#    "error": "Not authenticated"
# }

### test insertion of document if urban planner but some field not present

POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "username": "mario@test.it",
    "password": "pwd"
}

POST http://localhost:3001/api/documents
Content-Type: application/json

{
    "scale": "National",
    "issuance_Date": "04/2019",
    "language": "English",
    "pages": 50,
    "description": "Description of the document.",
    "idtype": 2
}

# 400 Bad Request
# {
#   "error": "The request body must contain all the fields"
# }

### test to get all documents to be done

### Test to get all types
GET http://localhost:3001/api/types

### Test to get a type by id
GET http://localhost:3001/api/types/1

### test to get all stakeholder

GET http://localhost:3001/api/stakeholders

### Test to get a stakeholder by id
GET http://localhost:3001/api/stakeholders/1



### TEST DOCUMENT CONNECTION API

### test to create a new connection between two documents
POST http://localhost:3001/api/document-connections
Content-Type: application/json

{
    "IdDocument1": 1,
    "IdDocument2": 2,
    "IdConnection": 1
}

