DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS DocumentConnection;
DROP TABLE IF EXISTS Stakeholder;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS TypeDocument;
DROP TABLE IF EXISTS Connection;
DROP TABLE IF EXISTS Document;

DELETE FROM DocumentConnection
SELECT * FROM Location

